### PR TITLE
Code highlighting adjustments

### PR DESCRIPTION
**Pull request by PragTob**
Allows you to adjust code highlighting colors, boldness etc - saved my ass over at rubyconf-lt (only FULLY works (with bold) once the PR over at shoes-highlighter is merged: shoes/shoes-highlighter#3)

### CODE REVIEW

**Comment by jasonrclark** [comment]
This will definitely come in handy. Curious to hear what trouble you ran into at rubyconf-lt that this helped out with!

**Comment by PragTob** [comment]
@jasonrclark the trouble was simply that the contrast in the beamer was practically non existant - it was a back projector, they often have those problems. The default highlighting scheme is with a light brown/yellow and that really could not be read... good thing I checked in the morning and my talk wasn't until after lunch. So I had enough time to fix shoes-highlighter and wingtips and get a good configuration up :+1: I was SO happy that highlighter already had the possibility to adjust colors etc.

**Comment by PragTob** [comment]
@jasonrclark what I did here seems good for me, to have one big configuration hash, I'll now head over to get_your_shoes_back_on and make adjustments there :)

**Comment by PragTob** [comment]
And a couple of more fixups, now it really should fly over at jasonrclark/get_your_shoes_back_on#4

**Comment by jasonrclark** [comment]
Like the changes, any reason to not merge and release 0.2.0 of `wingtips` (and the 1.0.1 of `shoes-highlighter`?)

Let me know if you'd like me to do the merge and release... will know shortly whether I'm giving the Shoes talk again anytime soon, and if so I look forward to testing out the new stuff in earnest!

**Comment by jasonrclark** [comment]
D'oh, missed that you'd released `shoes-highlighter` already. Thanks! :sparkles:

**Pull request merged**
